### PR TITLE
Add uvborder flag for cross udim check

### PR DESCRIPTION
**Pull request by deex2**
Sometime, UVs are so close to an udim border that we have false positive.
For example, create a simple sphere in Maya, `cmds.checkUV("|pSphere1", c=0)`, it will select top uvs.
Adding this flag (be default) ignore UVs close to the border (max distance)

### CODE REVIEW

**Comment by minoue** [comment]
Hi, Thank you for your pull request. 
At the moment, any UVs on the udim borders like those in "|pSphere1", are treated as errors. This is because substance painter can not import objects with those UVs. For example pSphere1 cannot be imported to substance painter.

But we often want UVs on borders on purpose, so I'm thinking it would be better to have another flag to include borders or not, based on uvBorderDistance.

**Comment by deex2** [comment]
Hi,

Thanks for the answer. What about a default value of 0.0?
I need to do some tests but a value of 0.0 is the same as the flag is not here.

**Comment by deex2** [comment]
Ok, so now the default value does nothing (this is like before).

**Comment by minoue** [comment]
Hi!, that actually sounds better so we can just change the number when we want to turn "ignore border" on.
Thank you for your change! : )

**Pull request merged**
