### PR TITLE
CMake review

### PR DESCRIPTION
**Pull request by bareya**
I checked the build system and it seems to be quite old with many code duplicates.

I re-arranged CMake code a bit and I added more verbose output.  Also, Maya root path is necessary to be added as a variable that is passed to CMake system:

```
cmake -DMAYA_ROOT_DIR=/path/to/maya/dir ..
``` 
When headers and libraries are found, then they are added to the Maya interface.

I haven't tested in on Windows nor MacOS.

### CODE REVIEW

**Comment by minoue** [comment]
I know there are duplicates, I'm not good at cmake...
Thanks for looking into this.
Let me test on my home Windows.

**Comment by bareya** [comment]
I just want to confirm that it builds on Windows 10 with VS2019.

~~But I haven't validated if the plugins are begin loaded, since I do not have Maya license.~~
I have checked and they load from plugin manager.

**Comment by minoue** [comment]
Hi, 
I got a openmp error in VS 2017. I don't have VS2019.

Do you think you can remove this line as openMP is not been used at the moment?
https://github.com/methodstudios/CheckTools/blob/937963b8485471a5ad1dab086ceae1b8ac5a3b34/uvOverlapChecker/CMakeLists.txt#L23

After removing the line, it worked.
Thanks

```
CMake Error at CMakeLists.txt:87 (add_library):
  Target "findUvOverlaps" links to target "OpenMP::OpenMP_CXX" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  uvOverlapChecker/CMakeLists.txt:5 (add_maya_library)
```

**Comment by bareya** [comment]
I made it as an issue for it #8. Very likely before we merge in this branch we would have to review all OpenMP dependencies.

I suspect that this is not VS issue, but version of CMake. What version of CMake are you using and which version of Maya are you compiling it against?

> Do you think you can remove this line as openMP is not been used at the moment?

I am not very familiar with OpenMP. For now we could say we can drop it, but check the aforementioned issue please. There is one pragma dependency on omp. I remember, on Linux, I got some linking errors if you remove linking with OpenMP library. 

I am more familiar with tbb, I could easily switch it tbb in the future.

**Comment by minoue** [comment]
Hi,
Sorry I thought OpenMP is not been used but it is.. I forgot it : (
I think I'm not using very latest of CMake in Windows. I'll check it later and try to update it.
In Linux, I use 3.15.0 without any issues.

**Comment by minoue** [comment]
Thank you for you advise.
I was using Cmake 3.8, but now I could built it without any issues with the latest CMake!
I reverted OpenMP removal as it seems to be fine for now.
Merged : )

**Pull request merged**
